### PR TITLE
Rlimit: Make rlimits POSIX-specific

### LINKED ISSUE #171: Make rlimits POSIX-specific
The [rlimit in oci-spec-rs](https://github.com/containers/oci-spec-rs/blob/d338cf83fe9a5c12d854068e8f36e28c51d4d6ae/src/runtime/process.rs#L77C25-L77C36) is designed for Linux and had limitations on other platforms, such as solaries. But the most important thing is oci-spec-rs has no alignment with [rlimit in OCI Spec](https://github.com/opencontainers/runtime-spec/blob/2d3f72ecad9e97c898e1eb04b899a51241f1cabd/specs-go/config.go#L84).

And a related MR(https://github.com/opencontainers/runtime-spec/commit/5292e9c82b79ea6a663b3c809751f8c0d3f910f0) for such problem.

### PR DESCRIPTION
**Pull request by Apokleos**
As described in the issue #171, oci-spec-rs need support POSI-specific Rlimit(PosixRlimit) but not LinuxRlimit.

Fixes #171

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]
Code LGTM.

We may want to add a bunch of cross compilation target to the CI. :thinking:

**Comment by Apokleos** [comment]
Hi @utam0k I need your help to review this PR. PTAL! Thx very much.

**Review by utam0k — APPROVED** [review]
Thanks!

**Comment by Mossaka** [comment]
I think this should be considered a breaking change since it modifies public API.

**Comment by utam0k** [comment]
> I think this should be considered a breaking change in the `v0.6.7` since it modifies public API.

@Mossaka Thanks for letting us know about this problem.
We know this PR led to the breaking change, but it's a problem that there is a no way to notice breaking changes for oci-spec-rs's users.

**Comment by utam0k** [comment]
I'll tackle the problem next weekend.

**Comment by Mossaka** [comment]
Is there a plan to release `v1.0.0`?

**Pull request merged**
