### PR TITLE
Release 0.6.0

### PR DESCRIPTION
**Pull request by saschagrunert**
Changes:
- https://github.com/containers/oci-spec-rs/pull/87
- https://github.com/containers/oci-spec-rs/pull/89
- https://github.com/containers/oci-spec-rs/pull/90
- https://github.com/containers/oci-spec-rs/pull/91

### CODE REVIEW

**Comment by cgwalters** [comment]
Is this release actually semver incompatible?  I didn’t think so

**Comment by saschagrunert** [comment]
> Is this release actually semver incompatible? I didn’t think so

In which way? We added new features and are still pre v1.0.0, so I thought 0.6.0 is the next logical version.

**Comment by cgwalters** [comment]
Per https://doc.rust-lang.org/cargo/reference/semver.html

> This guide uses the terms "major" and "minor" assuming this relates to a "1.0.0" release or later. Initial development releases starting with "0.y.z" can treat changes in "y" as a major release, and "z" as a minor release. "0.0.z" releases are always major changes. This is because Cargo uses the convention that only changes in the left-most non-zero component are considered incompatible.

It is quite normal in the crates ecosystem to introduce new APIs or new features in a `0.x.Z` i.e. patch release.  This of course leads into a whole other thread of how so many key crates have a pre-1.0 version and whether that really makes sense.

But I think a bottom line is: for crates with leading `0.` - I think it's more standard procedure to not casually bump semver.

**Comment by cgwalters** [comment]
To pick a random¹ example, see https://github.com/rust-random/rand/compare/0.8.3...0.8.4

A bunch of new APIs there, e.g. https://github.com/rust-random/rand/commit/91d7699a697eb303d689097c2733ae7d9f6af8cc

¹ 😉

**Comment by saschagrunert** [comment]
I'm not picky about this decision, so here we go: https://github.com/containers/oci-spec-rs/pull/93

**Pull request closed without merging**
