### PR TITLE
Release 0.7.0

### PR DESCRIPTION
**Pull request by saschagrunert**
Releasing the next version. Refers to #210

### CODE REVIEW

**Comment by saschagrunert** [comment]
Needs https://github.com/containers/oci-spec-rs/pull/215

**Review by flavio — APPROVED** [review]
LGTM

**Comment by saschagrunert** [comment]
Rebased on top of `main`, CI should be green now.

**Comment by saschagrunert** [comment]
Or not, let me check.

**Comment by utam0k** [comment]
Thanks, @saschagrunert. Sorry but I'm busy until next week

**Pull request merged**
