### PR TITLE
Release 0.6.5

### PR DESCRIPTION
**Pull request by rhatdan**
@jsturtevant @saschagrunert @tofay @cgwalters PTAL

### CODE REVIEW

**Comment by rhatdan** [comment]
https://github.com/albertofaria PTAL

**Comment by albertofaria** [comment]
I don't think this fixes the issue. Let me try sending a PR that also fixes the new lint errors.

**Comment by albertofaria** [comment]
Here it is: https://github.com/containers/oci-spec-rs/pull/161

**Comment by albertofaria** [comment]
This PR was superseded by #161.

**Pull request closed without merging**
