### PR TITLE
Rootless runtime::Spec generation

### LINKED ISSUE #130: Default Spec for rootless container
Is it possible to add something like oci_spec::runtime::Spec::default() but `rootless()/default_rootless()` for rootless containers?

### PR DESCRIPTION
**Pull request by lavrd**
According to `runc spec --rootless` I added possibility to generate rootless spec. 

Also, runc adds `cgroup` linux namespace to both specs, so I decided to add it too.

Closes #130

### CODE REVIEW

**Comment by saschagrunert** [comment]
@lavrd thank you for the PR, may I ask you to DCO-sign-off your commit?

**Comment by lavrd** [comment]
@saschagrunert, signed, looks like DCO check is ok

**Review by saschagrunert — CHANGES_REQUESTED** [review]
Can we have a test for that? :)

**Review by saschagrunert — APPROVED** [review]
LGTM

**Review by utam0k — APPROVED** [review]
Thanks

**Pull request merged**
